
server:
  port: 8081

movie:
  service:
    url: 'http://localhost:8082'

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/client
    username: postgres
    password: nonochais

  application:
    name: ms.client

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update